name: Build Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: |
        chmod +x package_extension.sh

    - name: Build extension
      run: |
        ./package_extension.sh
        ls -la

    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-notebook-extension
        path: web-notebook-extension.zip
        retention-days: 5

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "web-notebook-extension.zip"
        tag: "latest"
        name: "最新构建"
        body: "自动构建的最新版本"
        allowUpdates: true
        removeArtifacts: false
        token: ${{ secrets.GITHUB_TOKEN }}

